### ISSUE TITLE
Assets components stuck on loading animation when connected with Kepler without an account

### ISSUE THREAD

**Issue by mikeeus** [tendermint/vue#225] opened 2022-02-21 17:29 UTC
Steps to reproduce:
1. connect Kepler
2. click on "Data" to navigate to that route
3. then "Portfolio" to navigate back.

The assets component is stuck on loading animation.

![image](https://user-images.githubusercontent.com/16954412/155002811-c660a4bd-7d9e-42b5-92ef-49c1df969535.png)

**Comment by fadeev** [comment] 2022-02-21 19:35
It's essentially this issue: https://github.com/tendermint/vue/issues/204

@mikeeus the loading animation is a UI bug, but your account doesn't have tokens, hence the token transfer component is disabled. Use the faucet to send tokens to this address and please let us know if it works 🙏

**Comment by mikeeus** [comment] 2022-02-21 19:58
@fadeev Sending tokens to the address with the faucet worked!
So basically an account is "created" once a transaction referencing that account address is posted to the blockchain?

And should I close this issue because 204 addresses the ui bug?

**Comment by fadeev** [comment] 2022-02-21 20:05
> So basically an account is "created" once a transaction referencing that account address is posted to the blockchain?

This is exactly how it works.

**Comment by fadeev** [comment] 2022-02-21 20:06
Closing, because it's a duplicate of #204.

**Closed as completed by fadeev** 2022-02-21 20:06 UTC
